# Generated by Django 6.0.5 on 2026-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('bridal', 'Bridal Makeup'), ('party', 'Party Makeup'), ('mehndi', 'Mehndi Event'), ('walima', 'Walima Event'), ('engagement', 'Engagement Event')], default='bridal', max_length=20),
        ),
    ]
